In [159]:
import pandas as pd
import numpy as np

In [160]:
# Load BRFSS 2024 Dataset
df = pd.read_sas("../data/raw/LLCP2024.XPT")

print("Dataset Shape:", df.shape)

Dataset Shape: (457670, 301)

In [161]:
# Dataset Overview
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 457670 entries, 0 to 457669
Columns: 301 entries, _STATE to _AIDTST4
dtypes: float64(296), object(5)
memory usage: 1.0+ GB

In [162]:
# Confirm existence of target variable
'MEDCOST1' in df.columns

True

In [163]:
df['MEDCOST1'].value_counts(dropna=False)

MEDCOST1
2.0    412634
1.0     43363
7.0      1229
9.0       438
NaN         6
Name: count, dtype: int64

In [164]:
# Target variable proportions
df["MEDCOST1"].value_counts(normalize=True, dropna=False) * 100

MEDCOST1
2.0    90.159722
1.0     9.474731
7.0     0.268534
9.0     0.095702
NaN     0.001311
Name: proportion, dtype: float64

In [165]:
# Create dataframe of all column names
columns_df = pd.DataFrame({
    "Variable": df.columns
})
columns_df.head(20)

    Variable
0     _STATE
1     FMONTH
2      IDATE
3     IMONTH
4       IDAY
5      IYEAR
6   DISPCODE
7      SEQNO
8       _PSU
9   CTELENM1
10  PVTRESD1
11  COLGHOUS
12  STATERE1
13  CELPHON1
14   LADULT1
15  NUMADULT
16  RESPSLC1
17  LANDSEX3
18  SAFETIME
19  CTELNUM1

# Candidate Predictor Variables

## Target Variable
- MEDCOST1 — Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?

---

## Demographics
- SEXVAR — Sex of respondent
- MARITAL — Marital status
- EDUCA — Highest grade or year of school completed
- RENTHOM1 — Home ownership status (own or rent)
- _AGE80 — Imputed age in years (top coded at 80)
- _RACEGR3 — Five-level race/ethnicity classification

---

## Socioeconomic
- INCOME3 — Annual household income from all sources
- EMPLOY1 — Current employment status
- VETERAN3 — Ever served on active duty in the United States Armed Forces

---

## Healthcare Access
- PRIMINS2 — Current primary source of health care coverage
- PERSDOC3 — Personal doctor or health care provider status
- CHECKUP1 — Time since last routine medical checkup

---

## General Health Status
- GENHLTH — Self-reported general health
- PHYSHLTH — Number of days physical health was not good during the past 30 days
- MENTHLTH — Number of days mental health was not good during the past 30 days
- POORHLTH — Number of days poor physical or mental health limited usual activities

---

## Chronic Conditions
- CVDINFR4 — Ever told you had a heart attack (myocardial infarction)
- CVDCRHD4 — Ever told you had angina or coronary heart disease
- CVDSTRK3 — Ever told you had a stroke
- ASTHMA3 — Ever told you had asthma
- ASTHNOW — Still have asthma
- CHCSCNC1 — Ever told you had non-melanoma skin cancer
- CHCOCNC1 — Ever told you had melanoma or another type of cancer
- CHCCOPD3 — Ever told you had COPD, emphysema, or chronic bronchitis
- ADDEPEV3 — Ever told you had a depressive disorder
- CHCKDNY2 — Ever told you had kidney disease (excluding kidney stones, bladder infections, or incontinence)

---

## Health Behaviors
- EXERANY2 — Participated in physical activities or exercise during the past month (other than regular job)
- SMOKE100 — Smoked at least 100 cigarettes during lifetime
- _BMI5 — Body Mass Index (BMI)

---

## Potential Additional Variables
- LASTDEN4 — Time since last dental visit
- RMVTETH4 — Number of permanent teeth removed due to decay or gum disease

---

## Notes

These variables were selected based on their potential relationship to healthcare access barriers and delayed medical care due to cost. Final inclusion decisions will be made after evaluating missingness patterns, variable distributions, multicollinearity, and model performance.

In [166]:
# Candidate variables selected for initial review

candidate_vars = [

    "MEDCOST1",

    "SEXVAR",

    "MARITAL",

    "EDUCA",

    "RENTHOM1",

    "_AGE80",

    "_RACEGR3",

    "INCOME3",

    "EMPLOY1",

    "VETERAN3",

    "PRIMINS2",

    "PERSDOC3",

    "CHECKUP1",

    "GENHLTH",

    "PHYSHLTH",

    "MENTHLTH",

    "POORHLTH",

    "CVDINFR4",

    "CVDCRHD4",

    "CVDSTRK3",

    "ASTHMA3",

    "ASTHNOW",

    "CHCSCNC1",

    "CHCOCNC1",

    "CHCCOPD3",

    "ADDEPEV3",

    "CHCKDNY2",

    "EXERANY2",

    "SMOKE100",

    "_BMI5",

    "LASTDEN4",

    "RMVTETH4"

]

In [167]:
# Check whether all candidate variables exist in the dataset

missing_vars = [var for var in candidate_vars if var not in df.columns]

print("Missing variables:", missing_vars)

Missing variables: []

In [168]:
# Create candidate variable dataframe

candidate_df = df[candidate_vars].copy()

candidate_df.head()

,MEDCOST1,SEXVAR,MARITAL,EDUCA,RENTHOM1,_AGE80,_RACEGR3,INCOME3,EMPLOY1,VETERAN3,...,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,EXERANY2,SMOKE100,_BMI5,LASTDEN4,RMVTETH4
0,2.0,2.0,3.0,4.0,1.0,78.0,1.0,99.0,7.0,2.0,...,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2249.0,1.0,1.0
1,2.0,1.0,1.0,6.0,1.0,80.0,1.0,11.0,7.0,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2583.0,1.0,1.0
2,1.0,1.0,6.0,5.0,1.0,59.0,1.0,99.0,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2253.0,4.0,2.0
3,2.0,1.0,1.0,6.0,1.0,80.0,1.0,6.0,7.0,2.0,...,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2509.0,1.0,8.0
4,2.0,1.0,5.0,5.0,1.0,47.0,1.0,3.0,8.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1977.0,1.0,1.0

In [169]:
# Missingness percentage for candidate variables

missing_pct = (

    candidate_df

    .isna()

    .mean()

    .mul(100)

    .sort_values(ascending=False)

)

missing_pct

ASTHNOW     84.260056
POORHLTH    41.388118
_BMI5        9.403500
SMOKE100     6.305854
INCOME3      2.025258
EMPLOY1      0.721699
VETERAN3     0.269845
MARITAL      0.001966
RENTHOM1     0.001748
EDUCA        0.001529
CHCCOPD3     0.001529
CHCKDNY2     0.001311
CHCSCNC1     0.001311
MEDCOST1     0.001311
PHYSHLTH     0.001092
GENHLTH      0.001092
ADDEPEV3     0.001092
CHCOCNC1     0.001092
RMVTETH4     0.001092
CVDCRHD4     0.000655
CVDSTRK3     0.000655
ASTHMA3      0.000655
MENTHLTH     0.000655
PERSDOC3     0.000655
PRIMINS2     0.000655
EXERANY2     0.000655
CVDINFR4     0.000437
CHECKUP1     0.000437
LASTDEN4     0.000437
SEXVAR       0.000000
_RACEGR3     0.000000
_AGE80       0.000000
dtype: float64

In [170]:
# Value counts for each candidate variable

for var in candidate_vars:
    print("\n" + "=" * 70)
    print(f"Variable: {var}")

    print(f"Unique Values: {df[var].nunique(dropna=False)}")

    print("\nValue Counts:")
    print(df[var].value_counts(dropna=False))

    print("\nMissing %:")
    print(round(df[var].isna().mean() * 100, 2))

======================================================================
Variable: MEDCOST1
Unique Values: 5

Value Counts:
MEDCOST1
2.0    412634
1.0     43363
7.0      1229
9.0       438
NaN         6
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: SEXVAR

Unique Values: 2

Value Counts:
SEXVAR
2.0    240183
1.0    217487
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: MARITAL
Unique Values: 8

Value Counts:
MARITAL
1.0    229393
5.0     84851
2.0     58827
3.0     49161
6.0     21754
4.0      9462
9.0      4213
NaN         9
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: EDUCA
Unique Values: 8

Value Counts:
EDUCA
6.0    191549
5.0    120732
4.0    115877
3.0     17200
2.0      9226
9.0      2356
1.0       723
NaN         7
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: RENTHOM1
Unique Values: 6

Value Counts:
RENTHOM1
1.0    312589
2.0    118460
3.0     22677
9.0      2835
7.0      1101
NaN         8
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: _AGE80
Unique Values: 63

Value Counts:
_AGE80
80.0    41770
70.0    10484
65.0    10386
67.0     9810
68.0     9483
        ...
21.0     4290
22.0     4197
20.0     4159
19.0     4009
18.0     3773
Name: count, Length: 63, dtype: int64

Missing %:
0.0

======================================================================
Variable: _RACEGR3
Unique Values: 6

Value Counts:
_RACEGR3
1.0    329346
5.0     48646
2.0     35172
3.0     24917
4.0     10486
9.0      9103
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: INCOME3
Unique Values: 14

Value Counts:
INCOME3
7.0     60709
9.0     55778
8.0     51700
6.0     49686
5.0     41702
99.0    41041
77.0    37113
11.0    29694
10.0    26675
4.0     19841
3.0     13662
2.0     10542
1.0     10258
NaN      9269
Name: count, dtype: int64

Missing %:
2.03

======================================================================
Variable: EMPLOY1
Unique Values: 10

Value Counts:
EMPLOY1
1.0    186378
7.0    146916
2.0     39146
8.0     27758
5.0     17832
6.0     11473
4.0     10812
3.0      8953
9.0      5099
NaN      3303
Name: count, dtype: int64

Missing %:
0.72

======================================================================
Variable: VETERAN3
Unique Values: 5

Value Counts:
VETERAN3
2.0    402590
1.0     52504
NaN      1235
9.0      1154
7.0       187
Name: count, dtype: int64

Missing %:
0.27

======================================================================
Variable: PRIMINS2
Unique Values: 14

Value Counts:
PRIMINS2
1.0     155360
3.0     145567
2.0      38611
5.0      32847
88.0     25406
7.0      16939
77.0     12524
9.0      12329
10.0     10128
99.0      6017
8.0       1409
4.0        386
6.0        144
NaN          3
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: PERSDOC3
Unique Values: 6

Value Counts:
PERSDOC3
1.0    242393
2.0    154558
3.0     56106
7.0      3446
9.0      1164
NaN         3
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: CHECKUP1
Unique Values: 8

Value Counts:
CHECKUP1
1.0    370023
2.0     39655
3.0     21480
4.0     18395
7.0      4615
8.0      2783
9.0       717
NaN         2
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: GENHLTH
Unique Values: 8

Value Counts:
GENHLTH
3.0    156229
2.0    145791
4.0     67919
1.0     64217
5.0     22204
7.0       915
9.0       390
NaN         5
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: PHYSHLTH
Unique Values: 34

Value Counts:
PHYSHLTH
88.0    267576
30.0     36353
2.0      27903
1.0      18505
3.0      16919
5.0      16155
10.0     11130
15.0      9805
7.0       9385
4.0       9023
77.0      8765
20.0      6492
14.0      4667
6.0       2495
25.0      2494
99.0      2297
8.0       1856
12.0      1120
21.0       982
28.0       897
9.0        418
29.0       411
18.0       343
16.0       299
27.0       246
22.0       209
17.0       198
13.0       156
26.0       139
11.0       135
24.0       118
23.0       117
19.0        57
NaN          5
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: MENTHLTH
Unique Values: 34

Value Counts:
MENTHLTH
88.0    269909
30.0     27295
2.0      25180
5.0      21369
10.0     16465
3.0      15961
1.0      15412
15.0     15317
20.0      9721
4.0       8381
7.0       8277
77.0      5594
25.0      3346
14.0      2847
99.0      2559
6.0       2374
8.0       1873
12.0      1334
28.0       932
21.0       549
29.0       491
18.0       347
9.0        332
16.0       297
17.0       291
27.0       236
13.0       187
22.0       186
11.0       145
24.0       134
23.0       132
26.0       123
19.0        71
NaN          3
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: POORHLTH
Unique Values: 34

Value Counts:
POORHLTH
NaN     189421
88.0    136544
30.0     21013
2.0      16082
5.0      13184
1.0      12487
3.0      10938
15.0     10360
10.0     10316
20.0      6572
7.0       6257
4.0       6132
77.0      4219
14.0      2696
25.0      2354
6.0       1919
8.0       1583
99.0      1388
12.0       972
21.0       639
28.0       520
9.0        298
18.0       264
16.0       255
17.0       184
29.0       182
27.0       155
13.0       140
22.0       132
24.0       119
23.0       105
11.0       101
26.0        92
19.0        47
Name: count, dtype: int64

Missing %:
41.39

======================================================================
Variable: CVDINFR4
Unique Values: 5

Value Counts:
CVDINFR4
2.0    427883
1.0     26672
7.0      2857
9.0       256
NaN         2
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: CVDCRHD4
Unique Values: 5

Value Counts:
CVDCRHD4
2.0    424581
1.0     28511
7.0      4297
9.0       278
NaN         3
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: CVDSTRK3
Unique Values: 5

Value Counts:
CVDSTRK3
2.0    435557
1.0     20661
7.0      1244
9.0       205
NaN         3
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: ASTHMA3
Unique Values: 5

Value Counts:
ASTHMA3
2.0    383772
1.0     72037
7.0      1650
9.0       208
NaN         3
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: ASTHNOW
Unique Values: 5

Value Counts:
ASTHNOW
NaN    385633
1.0     49694
2.0     20267
7.0      2019
9.0        57
Name: count, dtype: int64

Missing %:
84.26

======================================================================
Variable: CHCSCNC1
Unique Values: 5

Value Counts:
CHCSCNC1
2.0    415539
1.0     39106
7.0      2761
9.0       258
NaN         6
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: CHCOCNC1
Unique Values: 5

Value Counts:
CHCOCNC1
2.0    400271
1.0     54953
7.0      2098
9.0       343
NaN         5
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: CHCCOPD3
Unique Values: 5

Value Counts:
CHCCOPD3
2.0    418575
1.0     36921
7.0      1921
9.0       246
NaN         7
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: ADDEPEV3
Unique Values: 5

Value Counts:
ADDEPEV3
2.0    358881
1.0     96125
7.0      2066
9.0       593
NaN         5
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: CHCKDNY2
Unique Values: 5

Value Counts:
CHCKDNY2
2.0    431939
1.0     23752
7.0      1715
9.0       258
NaN         6
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: EXERANY2
Unique Values: 5

Value Counts:
EXERANY2
1.0    350061
2.0    106294
7.0       860
9.0       452
NaN         3
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: SMOKE100
Unique Values: 5

Value Counts:
SMOKE100
2.0    258956
1.0    167242
NaN     28860
7.0      2062
9.0       550
Name: count, dtype: int64

Missing %:
6.31

======================================================================
Variable: _BMI5
Unique Values: 4199

Value Counts:
_BMI5
NaN       43037
2663.0     4428
2744.0     3378
2746.0     3364
2441.0     3300
          ...
4507.0        1
6299.0        1
4246.0        1
4595.0        1
4065.0        1
Name: count, Length: 4199, dtype: int64

Missing %:
9.4

======================================================================
Variable: LASTDEN4
Unique Values: 8

Value Counts:
LASTDEN4
1.0    311259
2.0     47521
4.0     45998
3.0     43098
7.0      4899
8.0      4088
9.0       805
NaN         2
Name: count, dtype: int64

Missing %:
0.0

======================================================================
Variable: RMVTETH4
Unique Values: 7

Value Counts:
RMVTETH4
8.0    241229
1.0    133728
2.0     46693
3.0     26563
7.0      8155
9.0      1297
NaN         5
Name: count, dtype: int64

Missing %:
0.0

In [171]:
for var in candidate_vars:
    print("\n" + "=" * 70)
    print(f"Variable: {var}")
    print(f"Unique Values: {df[var].nunique(dropna=False)}")
    print(f"Missing %: {round(df[var].isna().mean() * 100, 2)}")

    if df[var].nunique(dropna=False) > 50:
        print("\nSummary Statistics:")
        print(df[var].describe())
    else:
        print("\nValue Counts:")
        print(df[var].value_counts(dropna=False))

======================================================================
Variable: MEDCOST1
Unique Values: 5
Missing %: 0.0

Value Counts:
MEDCOST1
2.0    412634
1.0     43363
7.0      1229
9.0       438
NaN         6
Name: count, dtype: int64

======================================================================
Variable: SEXVAR
Unique Values: 2
Missing %: 0.0

Value Counts:
SEXVAR
2.0    240183
1.0    217487
Name: count, dtype: int64

======================================================================
Variable: MARITAL
Unique Values: 8
Missing %: 0.0

Value Counts:
MARITAL
1.0    229393
5.0     84851
2.0     58827
3.0     49161
6.0     21754
4.0      9462
9.0      4213
NaN         9
Name: count, dtype: int64

======================================================================
Variable: EDUCA
Unique Values: 8
Missing %: 0.0

Value Counts:
EDUCA
6.0    191549
5.0    120732
4.0    115877
3.0     17200
2.0      9226
9.0      2356
1.0       723
NaN         7
Name: count, dtype: int64

======================================================================
Variable: RENTHOM1
Unique Values: 6
Missing %: 0.0

Value Counts:
RENTHOM1
1.0    312589
2.0    118460
3.0     22677
9.0      2835
7.0      1101
NaN         8
Name: count, dtype: int64

======================================================================
Variable: _AGE80
Unique Values: 63
Missing %: 0.0

Summary Statistics:
count    457670.000000
mean         55.084784
std          18.127835
min          18.000000
25%          40.000000
50%          58.000000
75%          71.000000
max          80.000000
Name: _AGE80, dtype: float64

======================================================================
Variable: _RACEGR3
Unique Values: 6
Missing %: 0.0

Value Counts:
_RACEGR3
1.0    329346
5.0     48646
2.0     35172
3.0     24917
4.0     10486
9.0      9103
Name: count, dtype: int64

======================================================================
Variable: INCOME3
Unique Values: 14
Missing %: 2.03

Value Counts:
INCOME3
7.0     60709
9.0     55778
8.0     51700
6.0     49686
5.0     41702
99.0    41041
77.0    37113
11.0    29694
10.0    26675
4.0     19841
3.0     13662
2.0     10542
1.0     10258
NaN      9269
Name: count, dtype: int64

======================================================================
Variable: EMPLOY1
Unique Values: 10
Missing %: 0.72

Value Counts:
EMPLOY1
1.0    186378
7.0    146916
2.0     39146
8.0     27758
5.0     17832
6.0     11473
4.0     10812
3.0      8953
9.0      5099
NaN      3303
Name: count, dtype: int64

======================================================================
Variable: VETERAN3
Unique Values: 5
Missing %: 0.27

Value Counts:
VETERAN3
2.0    402590
1.0     52504
NaN      1235
9.0      1154
7.0       187
Name: count, dtype: int64

======================================================================
Variable: PRIMINS2
Unique Values: 14
Missing %: 0.0

Value Counts:
PRIMINS2
1.0     155360
3.0     145567
2.0      38611
5.0      32847
88.0     25406
7.0      16939
77.0     12524
9.0      12329
10.0     10128
99.0      6017
8.0       1409
4.0        386
6.0        144
NaN          3
Name: count, dtype: int64

======================================================================
Variable: PERSDOC3
Unique Values: 6
Missing %: 0.0

Value Counts:
PERSDOC3
1.0    242393
2.0    154558
3.0     56106
7.0      3446
9.0      1164
NaN         3
Name: count, dtype: int64

======================================================================
Variable: CHECKUP1
Unique Values: 8
Missing %: 0.0

Value Counts:
CHECKUP1
1.0    370023
2.0     39655
3.0     21480
4.0     18395
7.0      4615
8.0      2783
9.0       717
NaN         2
Name: count, dtype: int64

======================================================================
Variable: GENHLTH
Unique Values: 8
Missing %: 0.0

Value Counts:
GENHLTH
3.0    156229
2.0    145791
4.0     67919
1.0     64217
5.0     22204
7.0       915
9.0       390
NaN         5
Name: count, dtype: int64

======================================================================
Variable: PHYSHLTH
Unique Values: 34
Missing %: 0.0

Value Counts:
PHYSHLTH
88.0    267576
30.0     36353
2.0      27903
1.0      18505
3.0      16919
5.0      16155
10.0     11130
15.0      9805
7.0       9385
4.0       9023
77.0      8765
20.0      6492
14.0      4667
6.0       2495
25.0      2494
99.0      2297
8.0       1856
12.0      1120
21.0       982
28.0       897
9.0        418
29.0       411
18.0       343
16.0       299
27.0       246
22.0       209
17.0       198
13.0       156
26.0       139
11.0       135
24.0       118
23.0       117
19.0        57
NaN          5
Name: count, dtype: int64

======================================================================
Variable: MENTHLTH
Unique Values: 34
Missing %: 0.0

Value Counts:
MENTHLTH
88.0    269909
30.0     27295
2.0      25180
5.0      21369
10.0     16465
3.0      15961
1.0      15412
15.0     15317
20.0      9721
4.0       8381
7.0       8277
77.0      5594
25.0      3346
14.0      2847
99.0      2559
6.0       2374
8.0       1873
12.0      1334
28.0       932
21.0       549
29.0       491
18.0       347
9.0        332
16.0       297
17.0       291
27.0       236
13.0       187
22.0       186
11.0       145
24.0       134
23.0       132
26.0       123
19.0        71
NaN          3
Name: count, dtype: int64

======================================================================
Variable: POORHLTH
Unique Values: 34
Missing %: 41.39

Value Counts:
POORHLTH
NaN     189421
88.0    136544
30.0     21013
2.0      16082
5.0      13184
1.0      12487
3.0      10938
15.0     10360
10.0     10316
20.0      6572
7.0       6257
4.0       6132
77.0      4219
14.0      2696
25.0      2354
6.0       1919
8.0       1583
99.0      1388
12.0       972
21.0       639
28.0       520
9.0        298
18.0       264
16.0       255
17.0       184
29.0       182
27.0       155
13.0       140
22.0       132
24.0       119
23.0       105
11.0       101
26.0        92
19.0        47
Name: count, dtype: int64

======================================================================
Variable: CVDINFR4
Unique Values: 5
Missing %: 0.0

Value Counts:
CVDINFR4
2.0    427883
1.0     26672
7.0      2857
9.0       256
NaN         2
Name: count, dtype: int64

======================================================================
Variable: CVDCRHD4
Unique Values: 5
Missing %: 0.0

Value Counts:
CVDCRHD4
2.0    424581
1.0     28511
7.0      4297
9.0       278
NaN         3
Name: count, dtype: int64

======================================================================
Variable: CVDSTRK3
Unique Values: 5
Missing %: 0.0

Value Counts:
CVDSTRK3
2.0    435557
1.0     20661
7.0      1244
9.0       205
NaN         3
Name: count, dtype: int64

======================================================================
Variable: ASTHMA3
Unique Values: 5
Missing %: 0.0

Value Counts:
ASTHMA3
2.0    383772
1.0     72037
7.0      1650
9.0       208
NaN         3
Name: count, dtype: int64

======================================================================
Variable: ASTHNOW
Unique Values: 5
Missing %: 84.26

Value Counts:
ASTHNOW
NaN    385633
1.0     49694
2.0     20267
7.0      2019
9.0        57
Name: count, dtype: int64

======================================================================
Variable: CHCSCNC1
Unique Values: 5
Missing %: 0.0

Value Counts:
CHCSCNC1
2.0    415539
1.0     39106
7.0      2761
9.0       258
NaN         6
Name: count, dtype: int64

======================================================================
Variable: CHCOCNC1
Unique Values: 5
Missing %: 0.0

Value Counts:
CHCOCNC1
2.0    400271
1.0     54953
7.0      2098
9.0       343
NaN         5
Name: count, dtype: int64

======================================================================
Variable: CHCCOPD3
Unique Values: 5
Missing %: 0.0

Value Counts:
CHCCOPD3
2.0    418575
1.0     36921
7.0      1921
9.0       246
NaN         7
Name: count, dtype: int64

======================================================================
Variable: ADDEPEV3
Unique Values: 5
Missing %: 0.0

Value Counts:
ADDEPEV3
2.0    358881
1.0     96125
7.0      2066
9.0       593
NaN         5
Name: count, dtype: int64

======================================================================
Variable: CHCKDNY2
Unique Values: 5
Missing %: 0.0

Value Counts:
CHCKDNY2
2.0    431939
1.0     23752
7.0      1715
9.0       258
NaN         6
Name: count, dtype: int64

======================================================================
Variable: EXERANY2
Unique Values: 5
Missing %: 0.0

Value Counts:
EXERANY2
1.0    350061
2.0    106294
7.0       860
9.0       452
NaN         3
Name: count, dtype: int64

======================================================================
Variable: SMOKE100
Unique Values: 5
Missing %: 6.31

Value Counts:
SMOKE100
2.0    258956
1.0    167242
NaN     28860
7.0      2062
9.0       550
Name: count, dtype: int64

======================================================================
Variable: _BMI5
Unique Values: 4199
Missing %: 9.4

Summary Statistics:
count    414633.000000
mean       2855.680093
std         658.616131
min        1200.000000
25%        2414.000000
50%        2744.000000
75%        3175.000000
max        9984.000000
Name: _BMI5, dtype: float64

======================================================================
Variable: LASTDEN4
Unique Values: 8
Missing %: 0.0

Value Counts:
LASTDEN4
1.0    311259
2.0     47521
4.0     45998
3.0     43098
7.0      4899
8.0      4088
9.0       805
NaN         2
Name: count, dtype: int64

======================================================================
Variable: RMVTETH4
Unique Values: 7
Missing %: 0.0

Value Counts:
RMVTETH4
8.0    241229
1.0    133728
2.0     46693
3.0     26563
7.0      8155
9.0      1297
NaN         5
Name: count, dtype: int64

In [172]:
priority_vars = {
    "MEDCOST1": "Unable to see a doctor because of cost during the past 12 months (target variable)",
    "INCOME3": "Annual household income from all sources",
    "PRIMINS2": "Current primary source of health care coverage",
    "EMPLOY1": "Current employment status",
    "PERSDOC3": "Personal doctor or health care provider status",
    "CHECKUP1": "Time since last routine medical checkup",
    "GENHLTH": "Self-reported general health",
    "EDUCA": "Highest grade or year of school completed",
    "SEXVAR": "Sex of respondent",
    "MARITAL": "Marital status",
    "_AGE80": "Age in years",
    "_RACEGR3": "Race/ethnicity category"
}

In [173]:
secondary_vars = {
    "PHYSHLTH": "Number of days physical health was not good during the past 30 days",
    "MENTHLTH": "Number of days mental health was not good during the past 30 days",
    "RENTHOM1": "Home ownership status (own or rent)",
    "VETERAN3": "Ever served on active duty in the United States Armed Forces",
    "_BMI5": "Body Mass Index (BMI)",
    "SMOKE100": "Smoked at least 100 cigarettes during lifetime",
    "EXERANY2": "Participated in physical activities or exercise during the past month, other than regular job"
}

In [174]:
chronic_vars = {
    "CVDINFR4": "Ever told you had a heart attack (myocardial infarction)",
    "CVDCRHD4": "Ever told you had angina or coronary heart disease",
    "CVDSTRK3": "Ever told you had a stroke",
    "ASTHMA3": "Ever told you had asthma",
    "ASTHNOW": "Still have asthma",
    "CHCSCNC1": "Ever told you had non-melanoma skin cancer",
    "CHCOCNC1": "Ever told you had melanoma or another type of cancer",
    "CHCCOPD3": "Ever told you had COPD, emphysema, or chronic bronchitis",
    "ADDEPEV3": "Ever told you had a depressive disorder",
    "CHCKDNY2": "Ever told you had kidney disease (excluding kidney stones, bladder infections, or incontinence)"
}

In [175]:
# Priority Variable Review

In [176]:
for var, desc in priority_vars.items():
    print("\n" + "=" * 80)
    print(f"{var}: {desc}")
    print(df[var].value_counts(dropna=False))

================================================================================
MEDCOST1: Unable to see a doctor because of cost during the past 12 months (target variable)
MEDCOST1
2.0    412634
1.0     43363
7.0      1229
9.0       438
NaN         6
Name: count, dtype: int64

================================================================================
INCOME3: Annual household income from all sources
INCOME3
7.0     60709
9.0     55778
8.0     51700
6.0     49686
5.0     41702
99.0    41041
77.0    37113
11.0    29694
10.0    26675
4.0     19841
3.0     13662
2.0     10542
1.0     10258
NaN      9269
Name: count, dtype: int64

================================================================================
PRIMINS2: Current primary source of health care coverage
PRIMINS2
1.0     155360
3.0     145567
2.0      38611
5.0      32847
88.0     25406
7.0      16939
77.0     12524
9.0      12329
10.0     10128
99.0      6017
8.0       1409
4.0        386
6.0        144
NaN          3
Name: count, dtype: int64

================================================================================
EMPLOY1: Current employment status
EMPLOY1
1.0    186378
7.0    146916
2.0     39146
8.0     27758
5.0     17832
6.0     11473
4.0     10812
3.0      8953
9.0      5099
NaN      3303
Name: count, dtype: int64

================================================================================
PERSDOC3: Personal doctor or health care provider status
PERSDOC3
1.0    242393
2.0    154558
3.0     56106
7.0      3446
9.0      1164
NaN         3
Name: count, dtype: int64

================================================================================
CHECKUP1: Time since last routine medical checkup
CHECKUP1
1.0    370023
2.0     39655
3.0     21480
4.0     18395
7.0      4615
8.0      2783
9.0       717
NaN         2
Name: count, dtype: int64

================================================================================
GENHLTH: Self-reported general health
GENHLTH
3.0    156229
2.0    145791
4.0     67919
1.0     64217
5.0     22204
7.0       915
9.0       390
NaN         5
Name: count, dtype: int64

================================================================================
EDUCA: Highest grade or year of school completed
EDUCA
6.0    191549
5.0    120732
4.0    115877
3.0     17200
2.0      9226
9.0      2356
1.0       723
NaN         7
Name: count, dtype: int64

================================================================================
SEXVAR: Sex of respondent
SEXVAR
2.0    240183
1.0    217487
Name: count, dtype: int64

================================================================================
MARITAL: Marital status
MARITAL
1.0    229393
5.0     84851
2.0     58827
3.0     49161
6.0     21754
4.0      9462
9.0      4213
NaN         9
Name: count, dtype: int64

================================================================================
_AGE80: Age in years
_AGE80
80.0    41770
70.0    10484
65.0    10386
67.0     9810
68.0     9483
        ...
21.0     4290
22.0     4197
20.0     4159
19.0     4009
18.0     3773
Name: count, Length: 63, dtype: int64

================================================================================
_RACEGR3: Race/ethnicity category
_RACEGR3
1.0    329346
5.0     48646
2.0     35172
3.0     24917
4.0     10486
9.0      9103
Name: count, dtype: int64

In [177]:
[col for col in df.columns if "AGE" in col]

['DIABAGE4',
 'CNCRAGE',
 'CAGEG',
 '_AGEG5YR',
 '_AGE65YR',
 '_AGE80',
 '_AGE_G',
 '_LCSAGE']

In [178]:
[col for col in df.columns if "RACE" in col]

['_IMPRACE', '_CRACE1', '_MRACE1', '_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV']

In [179]:
df["_AGE80"].describe()

count    457670.000000
mean         55.084784
std          18.127835
min          18.000000
25%          40.000000
50%          58.000000
75%          71.000000
max          80.000000
Name: _AGE80, dtype: float64

In [180]:
df["_AGE80"].value_counts(dropna=False).sort_index()

_AGE80
18.0     3773
19.0     4009
20.0     4159
21.0     4290
22.0     4197
        ...
76.0     8109
77.0     8314
78.0     6395
79.0     5434
80.0    41770
Name: count, Length: 63, dtype: int64

In [181]:
age_vars = [
    "_AGE80",
    "_AGEG5YR",
    "_AGE65YR",
    "_AGE_G"
]

for var in age_vars:
    print("\n" + "="*50)
    print(var)
    print(df[var].value_counts(dropna=False))

==================================================
_AGE80
_AGE80
80.0    41770
70.0    10484
65.0    10386
67.0     9810
68.0     9483
        ...
21.0     4290
22.0     4197
20.0     4159
19.0     4009
18.0     3773
Name: count, Length: 63, dtype: int64

==================================================
_AGEG5YR
_AGEG5YR
10.0    47701
11.0    44774
9.0     43387
13.0    41756
12.0    36803
8.0     34936
7.0     31698
5.0     30899
1.0     29692
6.0     28968
4.0     28804
3.0     26237
2.0     23705
14.0     8310
Name: count, dtype: int64

==================================================
_AGE65YR
_AGE65YR
1.0    278326
2.0    171034
3.0      8310
Name: count, dtype: int64

==================================================
_AGE_G
_AGE_G
6.0    172826
5.0     80280
4.0     64458
3.0     60418
2.0     49994
1.0     29694
Name: count, dtype: int64

# Age Variable Selection

Several BRFSS age variables were reviewed. _AGE80 was selected for
modeling because it preserves the greatest level of age detail,
providing individual ages through 79 years and a top-coded category
for respondents aged 80 and older.

In [182]:
df["_RACEGR3"].value_counts(dropna=False)

_RACEGR3
1.0    329346
5.0     48646
2.0     35172
3.0     24917
4.0     10486
9.0      9103
Name: count, dtype: int64

In [183]:
race_vars = [
    "_IMPRACE",
    "_CRACE1",
    "_MRACE1",
    "_RACE",
    "_RACEG21",
    "_RACEGR3",
    "_RACEPRV"
]

for var in race_vars:
    print("\n" + "="*70)
    print(var)
    print(df[var].value_counts(dropna=False))

======================================================================
_IMPRACE
_IMPRACE
1.0    336908
5.0     48961
2.0     35559
6.0     16861
3.0     12760
4.0      6621
Name: count, dtype: int64

======================================================================
_CRACE1
_CRACE1
NaN     399071
1.0      41113
2.0       4877
7.0       3479
99.0      2717
4.0       2132
6.0       1412
3.0       1398
77.0      1046
5.0        425
Name: count, dtype: int64

======================================================================
_MRACE1
_MRACE1
1.0     358959
2.0      40393
4.0      13084
7.0      11680
6.0      10261
3.0       9156
99.0      5886
77.0      5439
5.0       2807
NaN          5
Name: count, dtype: int64

======================================================================
_RACE
_RACE
1.0    329346
8.0     48646
2.0     35172
4.0     12646
7.0     10486
9.0      9103
3.0      6460
6.0      3737
5.0      2074
Name: count, dtype: int64

======================================================================
_RACEG21
_RACEG21
1.0    329346
2.0    119221
9.0      9103
Name: count, dtype: int64

======================================================================
_RACEGR3
_RACEGR3
1.0    329346
5.0     48646
2.0     35172
3.0     24917
4.0     10486
9.0      9103
Name: count, dtype: int64

======================================================================
_RACEPRV
_RACEPRV
1.0    336908
8.0     48961
2.0     35559
4.0     12760
7.0     10486
3.0      6621
6.0      4301
5.0      2074
Name: count, dtype: int64

# Race Variable Selection

Several BRFSS race and ethnicity variables were reviewed.

_RACEGR3 was selected because it provides five interpretable race/ethnicity categories while maintaining sufficient representation across groups for analysis. More detailed race variables contained additional categories that would likely require consolidation during modeling, while broader variables combined groups in ways that could mask meaningful differences in healthcare access outcomes.

In [184]:
pd.crosstab(
    df["ASTHMA3"],
    df["ASTHNOW"],
    dropna=False
)

ASTHNOW    1.0    2.0   7.0  9.0     NaN
ASTHMA3
1.0      49694  20267  2019   57       0
2.0          0      0     0    0  383772
7.0          0      0     0    0    1650
9.0          0      0     0    0     208
NaN          0      0     0    0       3

## ASTHNOW Review

ASTHNOW is only asked of respondents who reported having asthma (ASTHMA3 = Yes). Therefore, the high percentage of missing values reflects BRFSS survey skip logic rather than respondent nonresponse.

Because ASTHMA3 already captures whether a respondent has ever been diagnosed with asthma, ASTHNOW may provide limited additional information while introducing additional preprocessing complexity. This variable will be evaluated further during feature selection and may be excluded from the final modeling dataset.

# Key EDA Findings and Next Steps

The 2024 BRFSS dataset contains 457,670 respondents and 301 variables. MEDCOST1 was confirmed as the supervised learning target variable.

The target variable is imbalanced: approximately 9.5% of respondents reported being unable to see a doctor because of cost, while approximately 90.2% reported no cost barrier. This means downstream model evaluation should not rely on accuracy alone.

All candidate variables selected for initial review were present in the dataset. Several BRFSS age and race variables were reviewed, and _AGE80 and _RACEGR3 were selected for the initial modeling dataset.

_AGE80 was selected because it preserves the greatest level of age detail available in the dataset, with individual ages through 79 and a top-coded category for respondents age 80 and older.

_RACEGR3 was selected because it provides five race/ethnicity categories while remaining easy to interpret. More detailed race variables contained additional categories that would likely require consolidation during modeling, while broader variables combined groups in ways that could mask meaningful differences in healthcare access outcomes.

Most variables have minimal true missingness, but ASTHNOW, POORHLTH, _BMI5, SMOKE100, and INCOME3 require additional review or preprocessing decisions. The ASTHMA3/ASTHNOW cross-tab suggests that ASTHNOW missingness is driven by BRFSS survey skip logic rather than respondent nonresponse.

Next steps:
1. Modularize feature lists into reusable functions.
2. Review special BRFSS response codes such as 7, 9, 77, 88, and 99.
3. Create recoded feature sets for modeling.
4. Document keep/drop/transform decisions for each candidate variable.
5. Create a cleaned modeling dataset for team handoff.